### ISSUE TITLE
User Interview Round 1

### ISSUE THREAD

**Issue by zhangyd** [vivianbuan/Search-Engine-for-Software#3]
Interview 2-3 people about their experience doing package searches. List of sample questions [https://docs.google.com/document/d/1l0c88H3EzDhlCxmBcCdCbcMFgvi88kTIlujGtOBGBgA/edit](url) 

![image](https://user-images.githubusercontent.com/3454952/31241966-5d575f58-a9ba-11e7-822c-b6dd1fe65d36.png)
![image](https://user-images.githubusercontent.com/3454952/31241973-645e6382-a9ba-11e7-8f20-5dcfaf602cfa.png)
![image](https://user-images.githubusercontent.com/3454952/31241979-6925bd02-a9ba-11e7-974e-d3eb3f540e9a.png)

**Comment by zhangyd** [comment]
**Pain points identified:**
- Too much time is spent on trying to read documents and testing out sample code when comparing multiple potential packages.
- Most documentation only provides guidance and instructions for situations in which everything works as expected. They are not very helpful when programmers encounter issues while using the package.
- When reading different result pages on Google, sometimes may lose track of a good article/tutorial after clicking through a bunch of potential helpful articles.
- Not able to formulate the right questions. A lot of the times it takes quite a few tries of rephrasing the questions to get answers that look promising.

**Comment by choo8** [comment]
**Pain points identified:**

- Examples in official documentation may not be as specific or well motivated as compared to those in blog posts. 
- Stackoverflow may not be the best place to go for opinion-based or subjective questions (e.g what is the best package for task xyz)
- Certain dependencies are not made explicit to user when user is going through tutorials on the package

**Comment by vivianbuan** [comment]
**Pain points identified:**
- Official documentation has issues such as outdated instruction or not instruction not detailed enough. In this case Stackoverflow offers better information.
- Stackoverflow has multiple posts providing different solution for a problem. Much time is spent on testing which one could work.
** Interesting Fact:**
- People usually already have preferred/possible packages in mind before searching.
- Image search and YouTube tutorials are sometimes useful.
- When performing the search, people usually jump to the code snippet or graph directly and ignore most text.

**Comment by choo8** [comment]
**Pain points identified from Andrew's interview transcripts:**
- Difficult to determine developers behind the software package, and whether they will continue developing it
- Some software packages do not have updated changelogs
- Bloggers may not fully understand software packages they are writing about, only can help you get started but might not help you perform your task well
- Conflicting or obsolete documentation may cause problems after you have invested time and effort into a particular software package 

**Interesting points interviewees brought up:**
- Copyright page indicator of how updated software is (last release date)
- "Gradware" - PhD students who write software packages for their thesis with no long term development goals
- Choice of software package might also be affected by non-web search factors like proficiency of colleagues or project mates in certain packages
- Forking might be a stronger signal for usage as compared to starring
- Software packages can be volatile, updates can break existing code
- Speed of issues being resolved on Github is important
- Reddit might be a source of questions on reliability and usability for software packages

**Comment by MSFeng** [comment]
Pain points identified:

- Spent too much time on comparing different approaches suggested by several answers on Stackoverflow. 
- Many tutorials are out of dates because of some software package used in certain step was updated and the authors of the tutorial didn't update the documentation corespondingly. 
- Some documentation provide poor installation instruction: do not have version suggestion, do not have step by step how-to instruction. Has to see answers in Stackoverflow for detail instruction
- Not always be able to find the best way to describe the problem, so have to do iterative search to improve the wording of query. 

Interesting points interviewees brought up:
- Prefer official documentation when they have the prior knowlegde of this package, just to see how a specifc function is using. When they explore for a new package to use, prefer blog posts and stackoverflow.
- Prefer to iteratively try sample code on stackoverflow until find the working one. Tend to use the method that they can understand.

**Comment by danisbet** [comment]
**Pain points Identified:**
•	Doesn’t trust example code from anywhere other than Github, documentation, and sometimes, Stack overflow
•	Documentation without details on each function isn’t always available (input parameters, use cases, output types). Sometimes, to figure out how to use a function the in-code commenting was the best source of understanding.
•	Would sometimes need to surf through Github to find examples of people forking and using a package for example code.
•	Since it’s difficult to analyze a package immediately, two of the three people I interviewed would download several packages and use each for different tasks, until finally narrowing down (in these cases, they weren’t completely aware that 1 package had all their use cases, so used different packages for different purposes) 
•	Determining the scope of a package. (ie. Was it just semantic analysis, ML models, parsing, or does it cover several of these)
**Interesting Points:** 
•	The three biggest indicators that my interviewees used for evaluation were: code examples, documentation, and popularity of package
•	The popularity of the package was measured in wildly different ways: recommendations on Stack overflow, number of stars on github, and “industry standard”
